require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 8

RSpec/ExampleLength:
  Enabled: false